# Generated by Django 4.0.2 on 2025-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ManyToManyField(related_name='portfolios', to='core.Category'),
        ),
    ]
